### ISSUE TITLE
Segmentation fault when pressing `o` or `O` on empty file

### ISSUE THREAD

**Issue by 07CalC** [Rational-Idiot/batata#1]
### description

when starting the editor with a new file, pressing `o` or `O` , the editor crashes with segmentation fault.

### expected behaviour

a new line should be inserted below or above the current line.

### cause

line 1838 of `batata.c`

```c
case 'o':
    E.cx = E.row[E.cy].size - 1;
    movecursor(ARROW_RIGHT);
    clearscreen();
    E.mode = 'i';
    insertnewline();
    break;
```
(similar for the case of `O`)

when the file is empty E.row is `NULL` and acccessing `E.row[E.cy].size` will cause a segmentation fault

### proposed solution

```c
  case 'o':
    if (E.numrows == 0) {
      E.cx = 0;
      insertnewline();
    } else {
      E.cx = E.row[E.cy].size - 1;
      movecursor(ARROW_RIGHT);
      clearscreen();
      insertnewline();
    }
    E.mode = 'i';
    break;
```

explicitly check for `E.numrows == 0` before accessing `E.row[E.cy].size` in the case of `o` and `O`.

**Comment by Rational-Idiot** [comment]
It is fixed now, the real problem was realloc (Called in the process of insertnewline) which is more likely to move the entire row when the file is shorter (eg- an empty file) that led to the initial pointer invalidation (dangling pointer)

It was fixed with reassigning the pointer after realloc

Thank you for pointing this,
I would wish to close this if there are no further comments

**Comment by 07CalC** [comment]
the issue still persists (on the latest commit) 

https://github.com/user-attachments/assets/0347d1bc-6e1c-4ad3-b410-7633a00458b2

**Comment by Rational-Idiot** [comment]
💀 
I was wrong, thank you for the detailed issue and the proposed solution, it should be implemented in Commit `af5287f` 
{repackage karna padega sab :( }

Your help in testing is very appreciated
